Entity Library
ValidHunters/Lua14 pull request #6
Opened 2024-05-13 12:40 UTC by mynameundefined

2024-05-13 20:46 UTC, Subversionary commented on Lua14/Lua/Libraries/Entity/EntityLibrary.Systems.cs
> +    }
Can those strings be put into the class instead? 
For example:

```cs
        private const string IdKey = "Id";
        private const string InitializeKey = "Initialize";
        private const string UpdateKey = "Update";
        private const string ShutdownKey = "Shutdown";
```

2024-05-13 20:46 UTC, Subversionary commented on Lua14/Lua/Libraries/Entity/EntityLibrary.Systems.cs
> +    }
To make the function be

```cs
    private static LuaSystemTable ToSystemTable(LuaTable table)
    {
        string id = GetStringValueFromTable(table, IdKey);

        return new LuaSystemTable
        {
            Id = id,
            Initialize = GetLuaFunction(table, InitializeKey),
            Update = GetLuaFunction(table, UpdateKey),
            Shutdown = GetLuaFunction(table, ShutdownKey)
        };
    }
```

2024-05-17 14:28 UTC, Subversionary requested changes
Base fundamentals should be documented

2024-05-17 14:28 UTC, Subversionary commented on Lua14/Lua/Userdata/ComponentIndexUserdata.cs
> +        var comp = Activator.CreateInstance(Type)!;
Adding an InvalidOperationException instead of asserting could be useful.
```suggestion
       var comp = Activator.CreateInstance(Type) 
               ?? throw new InvalidOperationException("Could not create instance of type.");
```

2024-05-17 14:28 UTC, Subversionary commented on Lua14/Lua/Userdata/EntityQueryUserdata.cs
> +                .ToArray();
Wouldn't an index instead of creating two arrays be better here?

2024-05-17 14:28 UTC, Subversionary commented on Lua14/Lua/Userdata/EntityQueryUserdata.cs
> +                }
1. The list should probably be initialized only once. You're creating a list of IComponent on every iteration of the while true loop.
2. This can be done in one go using an index going over _traitDicts

2024-05-17 14:28 UTC, Subversionary commented on Lua14/Lua/Userdata/EntityQueryUserdata.cs
> +                }
Won't this exit the loop when the first dictionary ends?

2024-05-17 14:28 UTC, Subversionary commented on Lua14/Lua/Userdata/EntityQueryUserdata.cs
> +public sealed class EntityQueryUserdata : LuaUserdata
Documentation

2024-05-17 15:06 UTC, mynameundefined commented on Lua14/Lua/Userdata/EntityQueryUserdata.cs
> +                }
yeah, as entity query does

2024-05-17 15:09 UTC, Subversionary commented on Lua14/Lua/Userdata/EntityQueryUserdata.cs
> +                }
Why have multiple dictionaries then?

2024-05-17 15:11 UTC, mynameundefined commented on Lua14/Lua/Userdata/EntityQueryUserdata.cs
> +                }
its an enumerator and a dictionary, not multiple dictionaries

2024-05-17 15:37 UTC, Subversionary approved these changes

2024-06-02 09:52 UTC, mynameundefined commented
redo later

2024-06-02 09:52 UTC, closed without merging